"""rename_user_auth_id

Revision ID: 42e97d2ae2e4
Revises: c6a9b7b4e2a3
Create Date: 2025-06-30 21:37:29.410632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e97d2ae2e4'
down_revision: Union[str, None] = 'c6a9b7b4e2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('user_auth_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('refresh_tokens_user_id_key'), 'refresh_tokens', type_='unique')
    op.create_unique_constraint(None, 'refresh_tokens', ['user_auth_id'])
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'user_auth', ['user_auth_id'], ['id'])
    op.drop_column('refresh_tokens', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'user_auth', ['user_id'], ['id'])
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.create_unique_constraint(op.f('refresh_tokens_user_id_key'), 'refresh_tokens', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('refresh_tokens', 'user_auth_id')
    # ### end Alembic commands ###
